### ISSUE TITLE
hotkey input via nodes

### ISSUE THREAD

**Issue by niewinny** [mx1001/Fidget#13]
# **TODO**
##### Command Nodes
- [x] Command
- [x] Switch
- [ ] Script
  - Needs to read internal and external script
  - Should detect imports and handle them appropiately
  - Node is possibly hidden from menu if the user preference option Advanced Mode _(todo)_ is disabled
- [ ] Operator
  - Needs to provide a search prop for available operators
  - Drop down menu that looks through operator types acts as a preliminary filter
  - Excludes operators that cannot be ran in the 3d view
  - Will need to look through bpy types
- [ ] Menu
  - Needs to provide a search prop for available menus
  - Drop down menu that looks through menu types acts as an initial filter
  - Excludes menus that can not be used in the 3d view
  - Will need to look through bpy types
- [ ] Property
  - Update a properties value (such as toggling the xray option of an object)
  - Should be able to paste commands copied from copy data path, will assume object property otherwise
  - Should detect property type and produce corresponding options
- [ ] Allow command nodes to be created with fed commands _via node catagories menu creation_
- [x] Create info fields for commands
- [x] Add press/release detection to command node sockets
##### Bool nodes
- [x] Compare
- [x] Active object
- [x] Active object type
- [x] Active object mode
- [ ] Objects visible
  - Used as the if visible objects check and the check for if the amount visible is of value
- [x] Objects selected
- [ ] Objects type
- [ ] Property
  - Check a properties value (such as whether object xray is enabled)
  - Should be able to paste commands copied from copy data path, will assume object property otherwise
  - Should detect property type and produce corresponding options
- [ ] Selection mode
  - Needs to check for modes this applies to
  - Check for whether in verts/edge/face selection mode as example
- [ ] Selection amount
  - Needs to check for modes this applies to
  - Check for number of verts/edges/faces selected as example
- [x] Statement bool node
##### Output
- [ ] Create initial write file functionality
- [ ] Create initial reset functionality
- [ ] Create initial build error catching
- [ ] Presets
- [ ] Migrate write and reset behavior path destination to user data folder?
- [ ] Script output node?
- [ ] Docs

# **Overview**
Ok, so this is the second idea. {I did push what I have to the nodes branch.) This time we will use nodes to set up the hotkeys for fidget.

The idea is simple we will allow the user to set up buttons via nodes.
In general, we need 4 type of nodes

- output
The output one will have a button with that will send the whole setup to the code.Aand 3 input sockets for fidget 3 buttons (top right and left
- input
input will allow writing bpy. lines of operators and will have 1 output settings
- if
if will have 2 input sockets and one output socket /we will have many of those with stuff like mode(edit/obj) number of obj and so on
- press/release
press/release will have 1 input and 1 output with a button to choose if its press or release.

So the general idea is to have some input nodes plugged to press/release each than those to the 'if ' node and from those to output

so at the end, they will generate code like that
![sublime_text_2017-08-20_00-44-37](https://user-images.githubusercontent.com/16288103/29490570-bb82197c-8540-11e7-8c91-736b6cfd1424.png)

I did basic implementation to check if it will work, but I have problems with how to transfer stuff from node to node via the socket or how to implement multi-line... 

So here is the general idea

![2](https://user-images.githubusercontent.com/16288103/29490585-063ef9b2-8541-11e7-85e3-01c1f21a34ca.jpg)

![1](https://user-images.githubusercontent.com/16288103/29490586-0d4fb192-8541-11e7-970f-0fe8122987fa.jpg)

So, for now, I did set up 1 string property in user preferences. When we press the button on the node we write the new string there. and finally, if the mouse is over the right button it exec that string. But of course, it needs to work like in the example above.

**Comment by niewinny** [comment]
I did push some initial design of how I would like it to work, yet it does produce some performance hits.

![2017-08-22_00-16-59](https://user-images.githubusercontent.com/16288103/29540752-57c96d18-86d0-11e7-881e-f7718685712c.gif)

**Comment by proxeIO** [comment]
Pushed some changes to the nodes branch, switch nodes should work and recursive node crawling is working, still more work to do ofcourse;

- [ ] Implement script node
- [ ] 
- [ ]

**Comment by proxeIO** [comment]
**TODO**: _(no specific order)_

- [ ] Implement script node
- [ ] Implement compare node
- [ ] Implement selected objects node
- [ ] Implement property state node
- [ ] Create initial write file functionality
- [ ] Create initial reset functionality
- [ ] Create initial build error catching
- [ ] Add press/release detection to command, script & switch node

**Comment by proxeIO** [comment]
Alright after some switch recursion fixings I have some proper output code in every situation I can think of, this is already being piped into the button command function, so everything should work as expected with the nodes offered except complete compare.

Here is some tests

Single switch:
![test1](https://user-images.githubusercontent.com/13005588/31294972-75e1bc24-aaa2-11e7-8bd4-a6e1fdafac3f.png)

Two switches:
![test2](https://user-images.githubusercontent.com/13005588/31294980-78b460a0-aaa2-11e7-9e0e-fa5220f66115.png)

Four switches some socketed into the bottom slot of other switches:
![test3](https://user-images.githubusercontent.com/13005588/31294995-81f99b58-aaa2-11e7-9a8e-c292dc3a5e7d.png)

And finally switches into switches into a single switch:
![test4](https://user-images.githubusercontent.com/13005588/31294994-81936216-aaa2-11e7-8fed-0e74a739b441.png)

Strictly speaking this code isn't meant to be optimal in the fashion a person would write it, it is instead meant to work and in any configuration conceivable so each if/else block has been dedicated to a node.

Need to add other bool nodes and implement the write out functionality, as it is the button is updated in memory and will behave as such until blender is restarted at which point it is reset to the defaults.

As a side note this code would _obviously_ break if there isn't an active object, there will be some checks added later on to prevent this.

**Comment by proxeIO** [comment]
Updated the images in my last post so that you can more easily compare the output code with the node setup.

**Comment by proxeIO** [comment]
Let me know what you guys think so far, I write and test on linux, so I guess there is a chance you can have a bug that I cant, let me know, I feel like the novelty factor in fidget will make it very popular, nodes setups being icing on the cake.

Been grinding away on name panel last few days, pushing hard for 1.8

**Comment by mx1001** [comment]
![blender_2017-10-12_00-27-58](https://user-images.githubusercontent.com/15908237/31480614-54522c2e-aee4-11e7-8379-eb89bf480fc2.png)

i am experiencing a little strangeness maybe i am not using it right but as you can see I get alot of console noise and an error at the end. I am also using the nodes branch but maybe im using the wrong one? id love to see some gifs of this thing in action

**Comment by proxeIO** [comment]
How strange I don't have that error at all, looking into it.

**Comment by proxeIO** [comment]
Pushed a few changes, I am not sure what the problem is as the node itself should have the toID method builtin and it works on my end, regardless I went ahead and emulated the behavior, kind of a shot in the dark since I don't have windows to test on, also noticed your using 2.79.1 this was tested on 2.79, seems unlikely that there would have been a change in these regards though.

**Comment by proxeIO** [comment]
Here it is in use
![demo](https://user-images.githubusercontent.com/13005588/31485112-4f6cd592-aef8-11e7-8e9c-28ef6300fc6a.gif)

**Comment by proxeIO** [comment]
Went ahead and pushed a tiny bug testing implementation; update now has a fallback that will function so long as the final output node name is _Output_ and the node tree is named _NodeTree_.

Try this and let me know what it prints out to the console.

**Comment by proxeIO** [comment]
Hey guys, I don't have windows atm so I can't exactly test this iteration out, works on linux, i assume then it should work on mac, occasionally this happens >.<

**Comment by proxeIO** [comment]
Did some testing using windows 10 in a virtual box, everything seemed to work fine >.<

**Comment by mx1001** [comment]
sorry for the lack of communication proxe i've been tied up but we have been planning a way forward with this that will make it easier on the users. Its working marvelously on my side. I think the text on the side wold be a good debug too where you could see the function without clicking the button like a previous version of fidget

but we do gotta polish this up since clones are starting to emerge. lets talk on g+ sometime as well!

**Comment by niewinny** [comment]
I still didn't find time to even check it. I will try to play with it this
weekend. hopefully... And I will try to write up some notes
general direction or at least on how I would like to see it.

but ye its great it's finally on the stage where we can start testing it
great work so far!

wt., 24 paź 2017 o 21:43 użytkownik proxe <notifications@github.com>
napisał:

**Comment by mx1001** [comment]
we should both try meeting at the same time haha. get proxe in on it too.

**Comment by proxeIO** [comment]
let me know when and Ill be there

**Comment by proxeIO** [comment]
Updated the todo list and checked a few things off
